// Search seeds for building a large, diverse catalog from the Spotify API.

// Broad style/genre search terms (kept generic so they return tracks in many markets).
export const GENRE_QUERIES: string[] = [
  "afrobeat", "afrobeats", "amapiano", "highlife", "soukous", "mbalax", "juju music",
  "fuji music", "benga", "taarab", "chimurenga", "kwaito", "gqom", "maskandi",
  "morna", "funaná", "coladeira", "raï", "gnawa", "chaabi", "malouf",
  "ethio-jazz", "tizita", "sega", "maloya", "salegy", "kwassa kwassa",
  "rumba congolaise", "makossa", "bikutsi", "zouglou", "coupé-décalé",
  "qawwali", "ghazal", "bhangra", "bollywood", "filmi", "carnatic", "hindustani",
  "baul", "dangdut", "keroncong", "gamelan", "luk thung", "mor lam", "pinoy",
  "cpop", "mandopop", "cantopop", "kpop", "jpop", "city pop", "enka", "trot",
  "throat singing", "mongolian folk", "tuvan", "central asian folk", "uyghur",
  "fado", "flamenco", "rebetiko", "laïko", "klezmer", "balkan brass",
  "turbo folk", "manele", "chalga", "tarab", "dabke", "persian pop", "dastgah",
  "anatolian rock", "turkish folk", "arabesque", "khaliji",
  "samba", "bossa nova", "mpb", "forró", "axé", "sertanejo", "pagode", "choro",
  "tango", "chamamé", "cumbia", "vallenato", "champeta", "salsa", "bachata",
  "merengue", "son cubano", "timba", "bolero", "ranchera", "mariachi", "norteño",
  "huayno", "andean folk", "marinera", "reggaeton", "dembow", "bomba", "plena",
  "reggae", "dancehall", "dub", "soca", "calypso", "zouk", "kompa", "bouyon",
  "celtic folk", "nordic folk", "joik", "polka", "schlager", "chanson",
  "hawaiian", "polynesian", "maori", "aboriginal", "didgeridoo",
  "world jazz", "global beats", "afro house", "desert blues", "tuareg",
];

// Spotify markets (ISO 3166-1 alpha-2) spanning the globe.
export const MARKETS: string[] = [
  "NG", "GH", "ZA", "KE", "TZ", "SN", "CI", "CM", "ET", "EG", "MA", "DZ", "TN",
  "ZW", "MZ", "AO", "CV", "MU",
  "IN", "PK", "BD", "LK", "NP", "ID", "MY", "PH", "TH", "VN", "KH", "MM",
  "CN", "TW", "HK", "JP", "KR", "MN", "KZ", "UZ",
  "TR", "IR", "IL", "SA", "AE", "LB", "JO", "IQ",
  "PT", "ES", "FR", "IT", "GR", "DE", "NL", "SE", "NO", "FI", "PL", "RO",
  "BG", "RS", "UA", "GE", "AM",
  "BR", "AR", "CL", "CO", "PE", "BO", "EC", "PY", "UY", "VE", "MX", "CU", "DO",
  "PR", "GT", "JM", "TT", "HT",
  "AU", "NZ", "US", "CA", "GB",
];

// Country-specific queries so the recommendation has an accurate country tag and
// surfaces genuinely local repertoire.
export const COUNTRY_QUERIES: { query: string; market: string; country: string }[] = [
  { query: "afrobeats naija", market: "NG", country: "Nigeria" },
  { query: "highlife ghana", market: "GH", country: "Ghana" },
  { query: "amapiano", market: "ZA", country: "South Africa" },
  { query: "benga kenya", market: "KE", country: "Kenya" },
  { query: "bongo flava", market: "TZ", country: "Tanzania" },
  { query: "mbalax senegal", market: "SN", country: "Senegal" },
  { query: "coupé-décalé", market: "CI", country: "Côte d'Ivoire" },
  { query: "makossa", market: "CM", country: "Cameroon" },
  { query: "ethiopian music", market: "ET", country: "Ethiopia" },
  { query: "egyptian shaabi", market: "EG", country: "Egypt" },
  { query: "chaabi maroc", market: "MA", country: "Morocco" },
  { query: "raï algérien", market: "DZ", country: "Algeria" },
  { query: "tunisian mezoued", market: "TN", country: "Tunisia" },
  { query: "zimdancehall chimurenga", market: "ZW", country: "Zimbabwe" },
  { query: "marrabenta", market: "MZ", country: "Mozambique" },
  { query: "semba kizomba", market: "AO", country: "Angola" },
  { query: "morna funaná", market: "CV", country: "Cape Verde" },
  { query: "sega maloya", market: "MU", country: "Mauritius" },
  { query: "bollywood hindi", market: "IN", country: "India" },
  { query: "coke studio pakistan", market: "PK", country: "Pakistan" },
  { query: "bangla band", market: "BD", country: "Bangladesh" },
  { query: "sinhala pop", market: "LK", country: "Sri Lanka" },
  { query: "nepali pop", market: "NP", country: "Nepal" },
  { query: "dangdut koplo", market: "ID", country: "Indonesia" },
  { query: "malaysian pop", market: "MY", country: "Malaysia" },
  { query: "opm pinoy", market: "PH", country: "Philippines" },
  { query: "luk thung thai", market: "TH", country: "Thailand" },
  { query: "v-pop vietnam", market: "VN", country: "Vietnam" },
  { query: "khmer song", market: "KH", country: "Cambodia" },
  { query: "burmese music", market: "MM", country: "Myanmar" },
  { query: "mandopop", market: "CN", country: "China" },
  { query: "mandopop taiwan", market: "TW", country: "Taiwan" },
  { query: "cantopop", market: "HK", country: "Hong Kong" },
  { query: "jpop city pop", market: "JP", country: "Japan" },
  { query: "kpop", market: "KR", country: "South Korea" },
  { query: "mongolian folk", market: "MN", country: "Mongolia" },
  { query: "kazakh pop", market: "KZ", country: "Kazakhstan" },
  { query: "uzbek pop", market: "UZ", country: "Uzbekistan" },
  { query: "anatolian rock", market: "TR", country: "Turkey" },
  { query: "persian pop", market: "IR", country: "Iran" },
  { query: "israeli mizrahi", market: "IL", country: "Israel" },
  { query: "khaliji", market: "SA", country: "Saudi Arabia" },
  { query: "khaleeji pop", market: "AE", country: "United Arab Emirates" },
  { query: "lebanese pop", market: "LB", country: "Lebanon" },
  { query: "dabke jordan", market: "JO", country: "Jordan" },
  { query: "iraqi maqam", market: "IQ", country: "Iraq" },
  { query: "fado", market: "PT", country: "Portugal" },
  { query: "flamenco", market: "ES", country: "Spain" },
  { query: "chanson française", market: "FR", country: "France" },
  { query: "canzone italiana", market: "IT", country: "Italy" },
  { query: "rebetiko laiko", market: "GR", country: "Greece" },
  { query: "schlager", market: "DE", country: "Germany" },
  { query: "nederpop", market: "NL", country: "Netherlands" },
  { query: "svensk folkmusik", market: "SE", country: "Sweden" },
  { query: "norsk folkemusikk", market: "NO", country: "Norway" },
  { query: "suomi iskelmä", market: "FI", country: "Finland" },
  { query: "muzyka ludowa polska", market: "PL", country: "Poland" },
  { query: "muzică populară", market: "RO", country: "Romania" },
  { query: "chalga", market: "BG", country: "Bulgaria" },
  { query: "narodna muzika", market: "RS", country: "Serbia" },
  { query: "ukrainian folk", market: "UA", country: "Ukraine" },
  { query: "georgian polyphony", market: "GE", country: "Georgia" },
  { query: "armenian duduk", market: "AM", country: "Armenia" },
  { query: "samba mpb", market: "BR", country: "Brazil" },
  { query: "tango argentino", market: "AR", country: "Argentina" },
  { query: "cueca chilena", market: "CL", country: "Chile" },
  { query: "cumbia vallenato", market: "CO", country: "Colombia" },
  { query: "huayno peruano", market: "PE", country: "Peru" },
  { query: "saya boliviana", market: "BO", country: "Bolivia" },
  { query: "música ecuatoriana", market: "EC", country: "Ecuador" },
  { query: "polca paraguaya", market: "PY", country: "Paraguay" },
  { query: "candombe uruguay", market: "UY", country: "Uruguay" },
  { query: "música llanera", market: "VE", country: "Venezuela" },
  { query: "mariachi ranchera", market: "MX", country: "Mexico" },
  { query: "son cubano timba", market: "CU", country: "Cuba" },
  { query: "bachata merengue", market: "DO", country: "Dominican Republic" },
  { query: "reggaeton bomba plena", market: "PR", country: "Puerto Rico" },
  { query: "marimba guatemala", market: "GT", country: "Guatemala" },
  { query: "reggae dancehall", market: "JM", country: "Jamaica" },
  { query: "soca calypso", market: "TT", country: "Trinidad and Tobago" },
  { query: "kompa haiti", market: "HT", country: "Haiti" },
  { query: "aboriginal didgeridoo", market: "AU", country: "Australia" },
  { query: "maori waiata", market: "NZ", country: "New Zealand" },
];
