import type { Song } from "./types.js";

// Hand-curated, intentionally non-Western-centric starter library.
// Real artists/songs with accurate metadata + descriptions.
// `spotifyTrackId` is filled later by the resolve/ingest pipeline (src/ingest.ts);
// until then the app links out to a Spotify search.
type SeedSong = Omit<Song, "id" | "spotifyTrackId" | "spotifyUrl">;

export const SEED_SONGS: SeedSong[] = [
  {
    title: "Yeke Yeke",
    artist: "Mory Kanté",
    artistDescription:
      "Guinean singer and kora virtuoso from a griot family, nicknamed the 'electronic griot' for fusing traditional Mandinka music with dance production.",
    songDescription:
      "A 1987 worldwide hit that became one of the first African singles to sell over a million copies, driven by a hypnotic kora riff.",
    country: "Guinea",
    language: "Maninka",
    genre: "African",
    subgenre: "Mandé / Afro-pop",
    albumName: "Akwaba Beach",
    albumType: "album",
    albumDescription: "Mory Kanté's 1987 breakthrough record blending griot tradition with European dance pop.",
    year: 1987,
  },
  {
    title: "Sodade",
    artist: "Cesária Évora",
    artistDescription:
      "The 'Barefoot Diva' of Cape Verde, who brought the melancholic morna genre to global audiences while performing without shoes in solidarity with the poor.",
    songDescription:
      "An aching morna about longing and homesickness (saudade) for the islands, and her signature song.",
    country: "Cape Verde",
    language: "Cape Verdean Creole",
    genre: "African",
    subgenre: "Morna",
    albumName: "Miss Perfumado",
    albumType: "album",
    albumDescription: "Her 1992 album that sold over 300,000 copies and made morna internationally known.",
    year: 1992,
  },
  {
    title: "Tezeta (Nostalgia)",
    artist: "Mulatu Astatke",
    artistDescription:
      "Ethiopian vibraphonist and the father of Ethio-jazz, who fused traditional Ethiopian scales with jazz, funk and Latin rhythms.",
    songDescription:
      "A languid, smoky instrumental in the tezeta mode, evoking memory and nostalgia — a cornerstone of Ethio-jazz.",
    country: "Ethiopia",
    language: "Instrumental",
    genre: "Jazz",
    subgenre: "Ethio-jazz",
    albumName: "Mulatu of Ethiopia",
    albumType: "album",
    albumDescription: "His landmark 1972 album recorded in New York that defined the Ethio-jazz sound.",
    year: 1972,
  },
  {
    title: "Independance Cha Cha",
    artist: "Le Grand Kallé et l'African Jazz",
    artistDescription:
      "Joseph Kabasele ('Le Grand Kallé') led African Jazz and is considered a father of modern Congolese rumba.",
    songDescription:
      "A celebratory 1960 rumba marking African independence movements, sung in Lingala and French.",
    country: "DR Congo",
    language: "Lingala",
    genre: "African",
    subgenre: "Congolese rumba",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1960,
  },
  {
    title: "Eh Hee",
    artist: "Huun-Huur-Tu",
    artistDescription:
      "Tuvan ensemble renowned for khoomei (throat singing), producing multiple pitches at once over horsehair fiddles.",
    songDescription:
      "A steppe-evoking piece showcasing overtone singing and the igil fiddle.",
    country: "Russia (Tuva)",
    language: "Tuvan",
    genre: "Folk",
    subgenre: "Throat singing (khoomei)",
    albumName: "The Orphan's Lament",
    albumType: "album",
    albumDescription: "A celebrated 1994 album of Tuvan throat singing and nomadic folk.",
    year: 1994,
  },
  {
    title: "Allah Hoo",
    artist: "Nusrat Fateh Ali Khan",
    artistDescription:
      "Pakistani qawwali maestro with an extraordinary vocal range, regarded as one of the greatest voices ever recorded.",
    songDescription:
      "An ecstatic devotional qawwali that builds to a trance-like climax praising the divine.",
    country: "Pakistan",
    language: "Urdu",
    genre: "Devotional",
    subgenre: "Qawwali",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1990,
  },
  {
    title: "Chan Chan",
    artist: "Buena Vista Social Club",
    artistDescription:
      "An ensemble of veteran Cuban musicians revived in the late 1990s, reviving son cubano for a global audience.",
    songDescription:
      "The gently swaying son that opens their famous album, written by Compay Segundo.",
    country: "Cuba",
    language: "Spanish",
    genre: "Latin",
    subgenre: "Son cubano",
    albumName: "Buena Vista Social Club",
    albumType: "album",
    albumDescription: "The Grammy-winning 1997 album that became a global phenomenon.",
    year: 1997,
  },
  {
    title: "Águas de Março",
    artist: "Elis Regina & Tom Jobim",
    artistDescription:
      "Elis Regina was Brazil's beloved interpreter; Antônio Carlos Jobim co-founded bossa nova.",
    songDescription:
      "A playful list-song of images from the Brazilian rainy season, considered one of the greatest Brazilian songs ever.",
    country: "Brazil",
    language: "Portuguese",
    genre: "Latin",
    subgenre: "MPB / bossa nova",
    albumName: "Elis & Tom",
    albumType: "album",
    albumDescription: "Their classic 1974 duet album recorded in Los Angeles.",
    year: 1974,
  },
  {
    title: "Gracias a la Vida",
    artist: "Violeta Parra",
    artistDescription:
      "Chilean folklorist and pioneer of the Nueva Canción movement who collected and renewed Chilean folk music.",
    songDescription:
      "A heartfelt hymn of gratitude to life, among the most covered Latin American songs of all time.",
    country: "Chile",
    language: "Spanish",
    genre: "Folk",
    subgenre: "Nueva canción",
    albumName: "Las Últimas Composiciones",
    albumType: "album",
    albumDescription: "Her final 1966 album, released shortly before her death.",
    year: 1966,
  },
  {
    title: "Mas Que Nada",
    artist: "Jorge Ben",
    artistDescription:
      "Brazilian singer-songwriter who fused samba with rock and soul, creating a uniquely propulsive style.",
    songDescription:
      "An infectious samba-rock anthem later made world-famous by Sérgio Mendes.",
    country: "Brazil",
    language: "Portuguese",
    genre: "Latin",
    subgenre: "Samba-rock",
    albumName: "Samba Esquema Novo",
    albumType: "album",
    albumDescription: "His influential 1963 debut.",
    year: 1963,
  },
  {
    title: "Lambada (Chorando Se Foi)",
    artist: "Kaoma",
    artistDescription:
      "French-Brazilian group that popularized the lambada dance craze worldwide in 1989.",
    songDescription:
      "A summer smash adapting a Bolivian melody into an irresistible dance number.",
    country: "Brazil",
    language: "Portuguese",
    genre: "Latin",
    subgenre: "Lambada",
    albumName: "Worldbeat",
    albumType: "album",
    albumDescription: "Kaoma's 1989 debut driven by the global hit single.",
    year: 1989,
  },
  {
    title: "Didi",
    artist: "Cheb Khaled",
    artistDescription:
      "Algerian singer known as the 'King of Raï', who modernized the rebellious Algerian street genre.",
    songDescription:
      "A 1992 international raï hit that brought North African pop to dancefloors worldwide.",
    country: "Algeria",
    language: "Arabic",
    genre: "African",
    subgenre: "Raï",
    albumName: "Khaled",
    albumType: "album",
    albumDescription: "His 1992 self-titled album, also home to 'Aïcha' later on.",
    year: 1992,
  },
  {
    title: "Enta Omri",
    artist: "Umm Kulthum",
    artistDescription:
      "The most revered singer in the Arab world, whose hour-long performances captivated millions across the 20th century.",
    songDescription:
      "An iconic long-form love song, regarded as a pinnacle of classical Arabic music.",
    country: "Egypt",
    language: "Arabic",
    genre: "Classical",
    subgenre: "Arabic classical / tarab",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1964,
  },
  {
    title: "Mustt Mustt",
    artist: "Nusrat Fateh Ali Khan & Michael Brook",
    artistDescription:
      "A collaboration between the qawwali legend and Canadian producer Michael Brook bridging Sufi devotion and ambient electronics.",
    songDescription:
      "A hypnotic Sufi groove later remixed by Massive Attack, a landmark of early world-fusion.",
    country: "Pakistan",
    language: "Urdu",
    genre: "World fusion",
    subgenre: "Qawwali fusion",
    albumName: "Mustt Mustt",
    albumType: "album",
    albumDescription: "The 1990 Real World album pairing Khan with Western production.",
    year: 1990,
  },
  {
    title: "Pata Pata",
    artist: "Miriam Makeba",
    artistDescription:
      "South African singer and activist known as 'Mama Africa', who brought South African music and anti-apartheid awareness to the world.",
    songDescription:
      "A buoyant township dance tune that became an international hit in 1967.",
    country: "South Africa",
    language: "Xhosa",
    genre: "African",
    subgenre: "Township / Afropop",
    albumName: "Pata Pata",
    albumType: "album",
    albumDescription: "Her 1967 album named after the hit single.",
    year: 1967,
  },
  {
    title: "Homeless",
    artist: "Ladysmith Black Mambazo",
    artistDescription:
      "South African male choral group masters of isicathamiya, a soft a cappella Zulu harmony tradition.",
    songDescription:
      "A gorgeous Zulu/English a cappella piece co-written with Paul Simon for Graceland.",
    country: "South Africa",
    language: "Zulu",
    genre: "African",
    subgenre: "Isicathamiya",
    albumName: "Graceland",
    albumType: "album",
    albumDescription: "Paul Simon's 1986 album that spotlighted South African musicians.",
    year: 1986,
  },
  {
    title: "Zombie",
    artist: "Fela Kuti",
    artistDescription:
      "Nigerian pioneer of Afrobeat and fearless political activist who fused Yoruba rhythms, jazz and funk into sprawling protest epics.",
    songDescription:
      "A scathing 1976 satire of the Nigerian military set to a relentless Afrobeat groove.",
    country: "Nigeria",
    language: "English / Pidgin",
    genre: "African",
    subgenre: "Afrobeat",
    albumName: "Zombie",
    albumType: "album",
    albumDescription: "His incendiary 1976 album that provoked a violent state reprisal.",
    year: 1976,
  },
  {
    title: "Madan",
    artist: "Salif Keita",
    artistDescription:
      "Malian 'Golden Voice of Africa', an albino nobleman who defied taboo to become a star of Mandé music.",
    songDescription:
      "A soaring, percussive Mandé pop anthem later widely sampled in dance music.",
    country: "Mali",
    language: "Bambara",
    genre: "African",
    subgenre: "Mandé pop",
    albumName: "Moffou",
    albumType: "album",
    albumDescription: "His acclaimed 2002 acoustic-leaning album.",
    year: 2002,
  },
  {
    title: "Ne La Thiass",
    artist: "Cheikh Lô",
    artistDescription:
      "Senegalese singer and Baye Fall mystic blending mbalax, Cuban son and Congolese rumba with a gentle voice.",
    songDescription:
      "The title track of his breakout album, a warm fusion of Senegalese grooves.",
    country: "Senegal",
    language: "Wolof",
    genre: "African",
    subgenre: "Mbalax",
    albumName: "Ne La Thiass",
    albumType: "album",
    albumDescription: "His 1996 Youssou N'Dour–produced debut.",
    year: 1996,
  },
  {
    title: "7 Seconds",
    artist: "Youssou N'Dour & Neneh Cherry",
    artistDescription:
      "Youssou N'Dour is Senegal's most famous voice and a mbalax innovator; here with Swedish-born singer Neneh Cherry.",
    songDescription:
      "A multilingual 1994 global hit about a newborn's innocence before the world's prejudices.",
    country: "Senegal",
    language: "Wolof / English / French",
    genre: "African",
    subgenre: "Mbalax / pop",
    albumName: "The Guide (Wommat)",
    albumType: "album",
    albumDescription: "Youssou N'Dour's 1994 album.",
    year: 1994,
  },
  {
    title: "Vache Aghdei",
    artist: "Sevara Nazarkhan",
    artistDescription:
      "Uzbek singer who modernizes Central Asian folk with the dutar lute and subtle electronics.",
    songDescription:
      "A delicate reworking of an Uzbek folk song produced by Hector Zazou.",
    country: "Uzbekistan",
    language: "Uzbek",
    genre: "Folk",
    subgenre: "Central Asian folk",
    albumName: "Yol Bolsin",
    albumType: "album",
    albumDescription: "Her internationally released 2003 album.",
    year: 2003,
  },
  {
    title: "Galang",
    artist: "M.I.A.",
    artistDescription:
      "British-Sri Lankan Tamil artist mixing dancehall, electro and global street sounds with political edge.",
    songDescription:
      "A raw, infectious debut single that announced a new globalized pop voice.",
    country: "Sri Lanka / UK",
    language: "English",
    genre: "Electronic",
    subgenre: "Worldbeat / grime-adjacent",
    albumName: "Arular",
    albumType: "album",
    albumDescription: "Her 2005 debut album.",
    year: 2005,
  },
  {
    title: "Jai Ho",
    artist: "A. R. Rahman",
    artistDescription:
      "Indian composer and 'Mozart of Madras' who reshaped Bollywood scoring with electronic and orchestral fusion.",
    songDescription:
      "The Oscar-winning, jubilant finale song from Slumdog Millionaire.",
    country: "India",
    language: "Hindi / Urdu / Punjabi",
    genre: "Soundtrack",
    subgenre: "Bollywood / filmi",
    albumName: "Slumdog Millionaire (Soundtrack)",
    albumType: "album",
    albumDescription: "The 2008 film score that won two Academy Awards.",
    year: 2008,
  },
  {
    title: "Chaiyya Chaiyya",
    artist: "Sukhwinder Singh & Sapna Awasthi",
    artistDescription:
      "A.R. Rahman composition performed by playback singers; famously filmed atop a moving train.",
    songDescription:
      "A Sufi-inflected filmi anthem celebrated for its rhythm and iconic picturization.",
    country: "India",
    language: "Hindi",
    genre: "Soundtrack",
    subgenre: "Bollywood / Sufi pop",
    albumName: "Dil Se..",
    albumType: "album",
    albumDescription: "The 1998 film soundtrack composed by A.R. Rahman.",
    year: 1998,
  },
  {
    title: "Sukiyaki (Ue o Muite Arukō)",
    artist: "Kyu Sakamoto",
    artistDescription:
      "Japanese pop star whose gentle 1961 ballad became the only Japanese-language song to top the US Billboard Hot 100.",
    songDescription:
      "A wistful tune about looking up while walking so tears won't fall, sung with disarming warmth.",
    country: "Japan",
    language: "Japanese",
    genre: "Pop",
    subgenre: "Kayōkyoku",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1961,
  },
  {
    title: "Plastic Love",
    artist: "Mariya Takeuchi",
    artistDescription:
      "Japanese singer-songwriter whose 1980s city pop was rediscovered globally via internet streaming decades later.",
    songDescription:
      "A glossy, melancholic city-pop classic that became a viral phenomenon in the 2010s.",
    country: "Japan",
    language: "Japanese",
    genre: "Pop",
    subgenre: "City pop",
    albumName: "Variety",
    albumType: "album",
    albumDescription: "Her 1984 album produced by husband Tatsuro Yamashita.",
    year: 1984,
  },
  {
    title: "Walang Kekek",
    artist: "Waljinah",
    artistDescription:
      "Waljinah is a revered Javanese singer of keroncong, a Portuguese-influenced Indonesian acoustic style.",
    songDescription:
      "An example of keroncong's gentle ukulele-and-cello sway and Javanese vocal ornamentation.",
    country: "Indonesia",
    language: "Javanese",
    genre: "Folk",
    subgenre: "Keroncong",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1970,
  },
  {
    title: "Misirlou (Surf)",
    artist: "Dick Dale",
    artistDescription:
      "Lebanese-American 'King of the Surf Guitar' who channeled Middle Eastern scales into reverb-soaked surf rock.",
    songDescription:
      "Pioneering surf instrumental built on rapid alternate picking and Arabic melodic influence.",
    country: "USA (Lebanese heritage)",
    language: "Instrumental",
    genre: "Rock",
    subgenre: "Surf rock",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1962,
  },
  {
    title: "Bésame Mucho",
    artist: "Consuelo Velázquez",
    artistDescription:
      "Mexican pianist and composer who wrote this bolero as a teenager; it became one of the most recorded songs in history.",
    songDescription:
      "A passionate bolero pleading for kisses as if it were the last night together.",
    country: "Mexico",
    language: "Spanish",
    genre: "Latin",
    subgenre: "Bolero",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1940,
  },
  {
    title: "La Llorona",
    artist: "Chavela Vargas",
    artistDescription:
      "Costa Rican-Mexican singer who reinvented ranchera, performing traditionally male songs with raw emotional power.",
    songDescription:
      "A haunting rendition of the folkloric lament of the 'weeping woman'.",
    country: "Mexico",
    language: "Spanish",
    genre: "Latin",
    subgenre: "Ranchera",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1993,
  },
  {
    title: "El Cóndor Pasa",
    artist: "Los Incas",
    artistDescription:
      "Andean ensemble who popularized the pan-flute zampoña and charango sound of the high Andes.",
    songDescription:
      "Based on a 1913 Peruvian melody, an emblem of Andean folk music worldwide.",
    country: "Peru",
    language: "Instrumental / Quechua",
    genre: "Folk",
    subgenre: "Andean / música criolla",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1963,
  },
  {
    title: "Lágrima",
    artist: "Amália Rodrigues",
    artistDescription:
      "The 'Queen of Fado', Portugal's defining voice of saudade-laden urban song.",
    songDescription:
      "A tear-soaked fado of love and loss delivered with her unmistakable vibrato.",
    country: "Portugal",
    language: "Portuguese",
    genre: "Folk",
    subgenre: "Fado",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1983,
  },
  {
    title: "To Ti Na Po",
    artist: "Bulgarian State Television Female Vocal Choir",
    artistDescription:
      "Bulgarian choir famous for 'Le Mystère des Voix Bulgares', using close dissonances and open-throated singing.",
    songDescription:
      "An otherworldly arrangement of Bulgarian folk harmony that stunned Western listeners.",
    country: "Bulgaria",
    language: "Bulgarian",
    genre: "Folk",
    subgenre: "Bulgarian polyphony",
    albumName: "Le Mystère des Voix Bulgares",
    albumType: "album",
    albumDescription: "The Grammy-winning compilation series of Bulgarian women's choral music.",
    year: 1975,
  },
  {
    title: "Misirlou",
    artist: "Greek rebetiko tradition",
    artistDescription:
      "Misirlou emerged from the Eastern Mediterranean rebetiko milieu before its global surf and Pulp Fiction fame.",
    songDescription:
      "A sinuous Eastern Mediterranean melody rooted in the rebetiko underground of Greek refugees.",
    country: "Greece",
    language: "Greek",
    genre: "Folk",
    subgenre: "Rebetiko",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1927,
  },
  {
    title: "Üsküdar'a Gider İken (Katibim)",
    artist: "Safiye Ayla",
    artistDescription:
      "Classic Turkish vocalist of the Ottoman/Republican era; this folk song is shared across the Balkans and Middle East.",
    songDescription:
      "A beloved Istanbul folk tune whose melody appears in many cultures from Bosnia to North Africa.",
    country: "Turkey",
    language: "Turkish",
    genre: "Folk",
    subgenre: "Turkish folk / türkü",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1949,
  },
  {
    title: "Soltan e Ghalbha",
    artist: "Aref",
    artistDescription:
      "Iranian pre-revolution pop singer whose romantic ballads defined an era of Persian popular music.",
    songDescription:
      "A sweeping 'Sultan of Hearts' love ballad emblematic of golden-age Iranian pop.",
    country: "Iran",
    language: "Persian",
    genre: "Pop",
    subgenre: "Persian pop",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1968,
  },
  {
    title: "Aïcha",
    artist: "Cheb Khaled",
    artistDescription:
      "Algerian 'King of Raï' whose crossover ballads brought the genre to French and global charts.",
    songDescription:
      "A tender French/Arabic ballad written by Jean-Jacques Goldman, a massive 1996 hit.",
    country: "Algeria",
    language: "Arabic / French",
    genre: "African",
    subgenre: "Raï / chanson",
    albumName: "Sahra",
    albumType: "album",
    albumDescription: "His 1996 album featuring the smash 'Aïcha'.",
    year: 1996,
  },
  {
    title: "Waka Waka (This Time for Africa)",
    artist: "Shakira ft. Freshlyground",
    artistDescription:
      "Colombian global pop star here teamed with South African band Freshlyground for the 2010 World Cup.",
    songDescription:
      "The official 2010 FIFA World Cup song built on the Cameroonian soukous tune 'Zangaléwa'.",
    country: "Colombia / South Africa",
    language: "English / Spanish",
    genre: "Pop",
    subgenre: "Afro-pop / world pop",
    albumName: "Sale el Sol",
    albumType: "album",
    albumDescription: "Shakira's 2010 album that included the World Cup anthem.",
    year: 2010,
  },
  {
    title: "Vivir Mi Vida",
    artist: "Marc Anthony",
    artistDescription:
      "American salsa star of Puerto Rican descent and the best-selling tropical salsa artist of all time.",
    songDescription:
      "An uplifting 2013 salsa anthem adapted from Khaled's 'C'est la vie'.",
    country: "Puerto Rico / USA",
    language: "Spanish",
    genre: "Latin",
    subgenre: "Salsa",
    albumName: "3.0",
    albumType: "album",
    albumDescription: "His 2013 return to salsa.",
    year: 2013,
  },
  {
    title: "Despacito",
    artist: "Luis Fonsi ft. Daddy Yankee",
    artistDescription:
      "Puerto Rican pop and reggaeton artists whose collaboration became a record-breaking global crossover.",
    songDescription:
      "The 2017 reggaeton-pop juggernaut that topped charts in dozens of countries.",
    country: "Puerto Rico",
    language: "Spanish",
    genre: "Latin",
    subgenre: "Reggaeton",
    albumName: "Vida",
    albumType: "album",
    albumDescription: "Luis Fonsi's 2019 album collecting the megahit.",
    year: 2017,
  },
  {
    title: "Gangnam Style",
    artist: "PSY",
    artistDescription:
      "South Korean rapper whose satirical dance hit introduced K-pop's viral potential to the West.",
    songDescription:
      "The 2012 phenomenon mocking Seoul's affluent Gangnam district, the first video to hit a billion YouTube views.",
    country: "South Korea",
    language: "Korean",
    genre: "Pop",
    subgenre: "K-pop",
    albumName: "Psy 6 (Six Rules), Part 1",
    albumType: "ep",
    albumDescription: "His 2012 EP featuring the worldwide hit.",
    year: 2012,
  },
  {
    title: "Arirang (traditional)",
    artist: "Korean folk tradition",
    artistDescription:
      "Arirang is the unofficial anthem of Korea, sung in countless regional variants and listed by UNESCO.",
    songDescription:
      "A poignant folk song of parting and longing, central to Korean identity.",
    country: "Korea",
    language: "Korean",
    genre: "Folk",
    subgenre: "Korean folk",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1926,
  },
  {
    title: "Mo Li Hua (Jasmine Flower)",
    artist: "Chinese folk tradition",
    artistDescription:
      "A centuries-old Chinese folk song known internationally, often performed at state occasions.",
    songDescription:
      "A delicate ode to the jasmine flower, one of the most recognizable Chinese melodies.",
    country: "China",
    language: "Mandarin",
    genre: "Folk",
    subgenre: "Chinese folk",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1804,
  },
  {
    title: "Urtiin Duu (Long Song)",
    artist: "Mongolian folk tradition",
    artistDescription:
      "The 'long song' (urtiin duu) is a Mongolian pastoral form with extended, ornamented vowels evoking the vast steppe.",
    songDescription:
      "An expansive, melismatic herder's song accompanied by the morin khuur horsehead fiddle.",
    country: "Mongolia",
    language: "Mongolian",
    genre: "Folk",
    subgenre: "Long song (urtiin duu)",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1990,
  },
  {
    title: "Treaty",
    artist: "Yothu Yindi",
    artistDescription:
      "Aboriginal Australian band blending Yolŋu songlines, didgeridoo and rock to campaign for Indigenous rights.",
    songDescription:
      "A 1991 anthem demanding a treaty for Aboriginal Australians, sung in Yolŋu Matha and English.",
    country: "Australia",
    language: "Yolŋu Matha / English",
    genre: "Rock",
    subgenre: "Aboriginal rock",
    albumName: "Tribal Voice",
    albumType: "album",
    albumDescription: "Their 1991 album that brought Aboriginal music to the charts.",
    year: 1991,
  },
  {
    title: "Hawai'i '78",
    artist: "Israel Kamakawiwoʻole",
    artistDescription:
      "Beloved Hawaiian singer and ukulele player, a gentle giant and symbol of Hawaiian sovereignty and aloha.",
    songDescription:
      "A mournful reflection on what Hawaiian ancestors would think of the islands today.",
    country: "USA (Hawaii)",
    language: "Hawaiian / English",
    genre: "Folk",
    subgenre: "Hawaiian",
    albumName: "Facing Future",
    albumType: "album",
    albumDescription: "His 1993 album, the best-selling Hawaiian record of all time.",
    year: 1993,
  },
  {
    title: "Veronica (Sega)",
    artist: "Ti Frère",
    artistDescription:
      "Mauritian legend of séga, the Creole dance music born from enslaved Africans on the island.",
    songDescription:
      "A foundational séga tune with ravanne drum and Creole lyrics.",
    country: "Mauritius",
    language: "Mauritian Creole",
    genre: "African",
    subgenre: "Séga",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1960,
  },
  {
    title: "Malagasy Guitar",
    artist: "D'Gary",
    artistDescription:
      "Malagasy guitarist famous for stunning open tunings that imitate the valiha zither and marovany.",
    songDescription:
      "Intricate fingerstyle guitar evoking the polyrhythms of southern Madagascar.",
    country: "Madagascar",
    language: "Malagasy",
    genre: "Folk",
    subgenre: "Malagasy",
    albumName: "Malagasy Guitar",
    albumType: "album",
    albumDescription: "His acclaimed 1992 solo guitar album.",
    year: 1992,
  },
  {
    title: "Nho Lobo (Funaná)",
    artist: "Bulimundo",
    artistDescription:
      "Cape Verdean band who electrified funaná, the fast accordion-driven dance music once banned by colonial authorities.",
    songDescription:
      "A driving funaná powered by gaita accordion and ferrinho scraper.",
    country: "Cape Verde",
    language: "Cape Verdean Creole",
    genre: "African",
    subgenre: "Funaná",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1981,
  },
  {
    title: "Sai",
    artist: "Kanda Bongo Man",
    artistDescription:
      "Congolese star who streamlined soukous into fast, guitar-led dance music ('kwassa kwassa').",
    songDescription:
      "An exuberant soukous track all sparkling guitars and dance rhythm.",
    country: "DR Congo",
    language: "Lingala",
    genre: "African",
    subgenre: "Soukous",
    albumName: "Kwassa Kwassa",
    albumType: "album",
    albumDescription: "His 1989 album that helped spread the kwassa kwassa dance.",
    year: 1989,
  },
  {
    title: "Shosholoza",
    artist: "South African choral tradition",
    artistDescription:
      "Shosholoza is a Nguni miners' work song that became an unofficial South African anthem of solidarity.",
    songDescription:
      "A call-and-response song that accompanied labor and now unites crowds and sports fans.",
    country: "South Africa",
    language: "Ndebele / Zulu",
    genre: "Folk",
    subgenre: "Work song",
    albumName: null,
    albumType: "single",
    albumDescription: null,
    year: 1950,
  },
];
